import type { Metadata } from 'next'
import { Ballet, Forum, PT_Serif, Afacad } from 'next/font/google'
import './globals.css'
import { NavHeader } from './components/nav-header/nav-header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const ballet = Ballet({ subsets: ['latin'] })
const forum = Forum({
  subsets: ['latin'],
  weight: '400',
})
const ptSerif = PT_Serif({
  subsets: ['latin'],
  weight: ['400', '700'],
})
const afacad = Afacad({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${forum.className} ${ballet.className} ${ptSerif.className} ${afacad.className}`}
    >
      <body className="h-[100%] bg-background text-base antialiased">
        <NavHeader />
        {children}
      </body>
    </html>
  )
}
